name: Deploy to Deta

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Push to Deta Space
        # You may pin to the exact commit or the version.
        # uses: neobrains/space-push@66542489a428050767cd300e9eb6f3c970d35775
        uses: neobrains/space-push@v0.0.1
        env:
          SPACE_ACCESS_TOKEN: ${{ secrets.SPACE_ACCESS_TOKEN }}
          SPACE_PROJECT_ID: ${{ secrets.SPACE_PROJECT_ID }}
        with:
          # Space access token
          space-access-token: ${{ env.SPACE_ACCESS_TOKEN }}
          # ID of the project to push to
          space-project-id: ${{ env.SPACE_PROJECT_ID }}

      - name: Deployed!
        run: echo Deployed!
